-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'MANAGER', 'SALES_REP', 'INVENTORY_CONTROLLER', 'SUPPORT', 'ACCOUNTANT', 'SUPPLIER_MANAGER', 'STAFF');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "address" TEXT,
ADD COLUMN     "phoneNumber" TEXT,
ADD COLUMN     "role" "UserRole" NOT NULL DEFAULT 'STAFF',
ALTER COLUMN "avatar" DROP NOT NULL;
