name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v3

      # Step 3: Install dependencies using Yarn
      - name: Install Dependencies
        run: yarn install

      # Step 4: Apply all pending migrations to the database using Prisma
      - name: Apply Database Migrations
        run: yarn prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          DIRECT_URL: ${{ secrets.PROD_DIRECT_URL }}
