name: Deploy Database Migrations

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
      DIRECT_URL: ${{ secrets.PROD_DIRECT_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn prisma:generate

      - name: Run Linter
        run: yarn lint

      - name: Run Build
        run: yarn build

      - name: Apply Database Migrations
        run: yarn prisma migrate deploy
